### PR TITLE
Fix CAF found status in build summary

### PR DESCRIPTION
**Pull request by josephnoir**
The build summary claims  `CAF: no` if the CAF core, io and test modules were found but the OpenCL module is not available, as the optional find overwrites the original `CAF_FOUND` variable. This PR saves the variable and restores it after the second find call.

### CODE REVIEW

**Comment by josephnoir** [comment]
You could also just print the `${caf_dir}`in the build summary, as the script will terminate if the CAF modules were not found.

**Comment by mavam** [comment]
Thanks for the fix.

**Comment by josephnoir** [comment]
Oh damn, all the mails from Jenkins. Seems to be related to SSL.

**Comment by mavam** [comment]
I'm not surprised that OpenSSL is hard to use (i) across platforms, and (ii) across multiple versions. 😉

**Pull request merged**
