### PR TITLE
Replace typename with class in template<typename ...

### PR DESCRIPTION
**Pull request by SebastianWoelke**

### CODE REVIEW

**Comment by SebastianWoelke** [comment]
I worte a python script, which searches every line in the code base, looks for the keyword **template** and then simply replaces **typename**  with **class**

`if "template" in line:`
`new_lines.append(line.replace("typename", "class")`

But I realize now that I forgot multilines template like in vast/json.hpp:166

**Comment by mavam** [comment]
> But I realize now that I forgot multilines template

Yeah, these are a bit harder to deal with.

My initial thought was to replace *all* occurrences of `typename` with `class`, and then find a way to filter dependent types. This yields no false negatives.

**Comment by SebastianWoelke** [comment]
I fixed my script, multiline template expressions are included now.

In this context I stumpled over the file libvast/vast/detail/chrono_io.hpp
Is this file still in use?
Line 88 should not compile because of a missing arrow bracket.

**Comment by mavam** [comment]
> I fixed my script, multiline template expressions are included now.

Great to hear!

> In this context I stumpled over the file libvast/vast/detail/chrono_io.hpp
> Is this file still in use?
> Line 88 should not compile because of a missing arrow bracket.

The way to check this is by looking whether it is included anywhere. This reveals that `/vast/concept/printable/std/chrono.hpp` uses it.

If everything compiles now, I'll go ahead an merge.

**Comment by SebastianWoelke** [comment]
Everything compiles and vast-test executes successfully

**Pull request merged**
