### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by JasperEm**

### CODE REVIEW

**Comment by JasperEm** [comment]
I will adding a test case in the next days.

**Comment by JasperEm** [comment]
I hope it is done :smile:

**Comment by JasperEm** [comment]
*  I changed the test to use only one view.
*  I was not sure that `++it` calls implicit the `increment / decrement` functions.

**Comment by Neverlord** [comment]
> I was not sure that ++it calls implicit the increment / decrement functions.

Well, you _do_ have the source code... 😉

Thanks for the patch! One last comment: for future contributions please follow our [guideline for git commit messages](https://github.com/vast-io/vast/blob/master/CONTRIBUTING.md#commit-messages), (e.g. "Improve tests" or, even better "Use operators instead of iterator member functions", instead of "improved tests").

**Comment by JasperEm** [comment]
Thx for your review and I will follow the guideline next time :wink:

**Pull request merged**
